name: Deploy to Neocities
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Neocities CLI
        # run: npm install -g neocities
        run: pip3 install neocities

      - name: Deploy
        env:
          NEOCITIES_API_KEY: ${{ secrets.NEOCITIES_API_KEY }}
        run: neocities deploy ./ --key $NEOCITIES_API_KEY
