name: Deploy to Neocities

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. コードをチェックアウト
      - uses: actions/checkout@v3

      # 2. Ruby 環境をセットアップ
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.x'       # 好きなバージョンに置き換えて OK

      # 3. neocities gem をインストール
      - name: Install Neocities CLI (Ruby)
        run: |
          gem install neocities

      # 4. 実際にサイトをアップロード
      - name: Deploy to Neocities
        env:
          NEOCITIES_API_KEY: ${{ secrets.NEOCITIES_API_KEY }}
        run: |
          # --dir オプションで指定したディレクトリを再帰的にアップ
          neocities push --dir=./ --key $NEOCITIES_API_KEY
